syntax = "proto3";

package inventory;

service InventoryService {
  rpc CheckAvailability (InventoryRequest) returns (InventoryResponse);
  rpc ReserveItems (ReserveRequest) returns (ReserveResponse);
}

message InventoryRequest {
  map<string, int32> items = 1;
}

message InventoryResponse {
  map<string, bool> availability = 1;
}

message ReserveRequest {
  map<string, int32> items = 1;
}

message ReserveItemResult {
  string productId = 1;
  bool success = 2;
  string message = 3;
}

message ReserveResponse {
  bool overallSuccess = 1;
  repeated ReserveItemResult results = 2;
}
